// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWD392.OutfitBox.DataLayer.Databases.Redis;

#nullable disable

namespace SWD392.OutfitBox.DataLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240610135443_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Area");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Ho Chi Minh",
                            District = "Thu Duc"
                        },
                        new
                        {
                            Id = 2,
                            City = "Binh Duong",
                            District = "Di An"
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Brand");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = " Explosive within the Vietnamese fashion community in 2013, Nosbyn captured the hearts of young fashion enthusiasts with its stylish yet basic items. Leading the way were its signature solid-colored crop tops, which remained a prominent fixture even after three years of development. Today, Nosbyn continues to hold a strong position in the hearts of Vietnamese fashionistas.",
                            ImageUrl = "https://nosbyn.com/",
                            IsFeatured = false,
                            Name = "NOSBYN",
                            Status = 1
                        },
                        new
                        {
                            ID = 2,
                            Description = "The BlueTshirt, established in 2012, initially introduced simple t-shirt designs with inspiring slogans to the Vietnamese market. The brand's designs strike a perfect balance between elegance and a free-spirited nature, reflecting the personality of its founder. Whether you are a gentle and graceful woman or someone with a strong individualistic style, The BlueTshirt offers a wide range of products to cater to your preferences.",
                            ImageUrl = "https://thebluetshirt.com/",
                            IsFeatured = false,
                            Name = "THE BLUE T-SHIRT",
                            Status = 1
                        },
                        new
                        {
                            ID = 3,
                            Description = "With an unwavering commitment to quality craftsmanship, ethical practices, and timeless design, O4R is poised to become the go-to destination for fashion-conscious individuals seeking both substance and style",
                            ImageUrl = "https://thebluetshirt.com/",
                            IsFeatured = false,
                            Name = "OUTFIT4RENT",
                            Status = 1
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "T-Shirt,Vest,Polo,Smock,...",
                            ImageUrl = "",
                            IsFeatured = false,
                            Name = "Shirt",
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            Description = "Gauchos,Jeans,Trousers,...",
                            ImageUrl = "",
                            IsFeatured = false,
                            Name = "Short",
                            Status = 0
                        },
                        new
                        {
                            ID = 3,
                            Description = "Skater,Circle,Aline,Maxi,Sarong,...",
                            ImageUrl = "",
                            IsFeatured = false,
                            Name = "Skirt",
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            Description = "A-line,Empire,Tent,Princess,Shift,...",
                            ImageUrl = "",
                            IsFeatured = false,
                            Name = "Dress",
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            Description = "Ao dai,Traditional clothers,...",
                            ImageUrl = "",
                            IsFeatured = false,
                            Name = "Costumes",
                            Status = 0
                        },
                        new
                        {
                            ID = 6,
                            Description = "Sunglasses,Tie,Watch,Bow,...",
                            ImageUrl = "",
                            IsFeatured = false,
                            Name = "Accessories",
                            Status = 0
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.CategoryPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("MaxAvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PackageId");

                    b.ToTable("CategoryPackages");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            MaxAvailableQuantity = 3,
                            PackageId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            MaxAvailableQuantity = 3,
                            PackageId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            MaxAvailableQuantity = 3,
                            PackageId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            MaxAvailableQuantity = 3,
                            PackageId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            MaxAvailableQuantity = 3,
                            PackageId = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            MaxAvailableQuantity = 2,
                            PackageId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            MaxAvailableQuantity = 2,
                            PackageId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            MaxAvailableQuantity = 2,
                            PackageId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            MaxAvailableQuantity = 2,
                            PackageId = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            MaxAvailableQuantity = 4,
                            PackageId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            MaxAvailableQuantity = 4,
                            PackageId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            MaxAvailableQuantity = 4,
                            PackageId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            MaxAvailableQuantity = 4,
                            PackageId = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 6,
                            MaxAvailableQuantity = 4,
                            PackageId = 3,
                            Status = 1
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MoneyInWallet")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OTP")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Dong Nai",
                            Email = "Khanhvhdse173550@fpt.edu.vn",
                            MoneyInWallet = 1000L,
                            Name = "Khanh Sky",
                            OTP = 111111L,
                            Password = "123456",
                            Phone = "0325739910",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "HCM",
                            Email = "User2@gmail.com",
                            MoneyInWallet = 100L,
                            Name = "User2",
                            OTP = 222222L,
                            Password = "123456",
                            Phone = "123",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "HCM",
                            Email = "User3@gmail.com",
                            MoneyInWallet = 100L,
                            Name = "User3",
                            OTP = 333333L,
                            Password = "123456",
                            Phone = "123",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "HCM",
                            Email = "User4gmail.com",
                            MoneyInWallet = 100L,
                            Name = "User4",
                            OTP = 444444L,
                            Password = "123456",
                            Phone = "123",
                            Status = 1
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.CustomerPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime2");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PackageId");

                    b.HasIndex("TransactionId");

                    b.ToTable("CustomerPackage");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            DateFrom = new DateTime(2024, 6, 10, 20, 54, 42, 970, DateTimeKind.Local).AddTicks(338),
                            DateTo = new DateTime(2024, 7, 10, 20, 54, 42, 970, DateTimeKind.Local).AddTicks(364),
                            PackageId = 1,
                            PackageName = "Newcomer Trial",
                            Price = 200.0,
                            ReceiverAddress = "Nha Van Hoa Sinh Vien",
                            ReceiverName = "Khanh Sky",
                            ReceiverPhone = "0325739910",
                            Status = 1,
                            TransactionId = 1
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Deposit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmountMoney")
                        .HasColumnType("float");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Deposits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountMoney = 20.0,
                            CustomerId = 1,
                            Date = new DateTime(2024, 6, 10, 20, 54, 42, 970, DateTimeKind.Local).AddTicks(655),
                            Type = "Khuyen Mai"
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.FavouriteProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("FavouriteProduct");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Image", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IdProduct");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IdProduct = 1,
                            Link = "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-lvmx2enml619c4"
                        },
                        new
                        {
                            ID = 2,
                            IdProduct = 1,
                            Link = "https://down-vn.img.susercontent.com/file/vn-11134201-7r98o-lvmx2hoo6zzv29"
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.ItemInUserPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateGive")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateReceive")
                        .HasColumnType("datetime2");

                    b.Property<double>("Deposit")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TornMoney")
                        .HasColumnType("float");

                    b.Property<int>("UserPackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserPackageId");

                    b.ToTable("ItemInUserPackages");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableRentDays")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumOfProduct")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableRentDays = 30,
                            Description = "The new customer can use to experience, with total 4 product in 4 category: Shirt,Short,Skirt,Dress. Max product in each category is 2",
                            ImageUrl = "",
                            IsFeatured = false,
                            Name = "Newcomer Trial",
                            NumOfProduct = 4,
                            Price = 200.0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailableRentDays = 30,
                            Description = "Customers will feel comfortable and appreciate the size and quality of the outfit, The package will provide 8 products in 5 parkage:Shirt,Short,Skirt,Dress,Accessories.  Max product in each category is 3",
                            ImageUrl = "",
                            IsFeatured = false,
                            Name = "Basic Package",
                            NumOfProduct = 8,
                            Price = 600.0,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            AvailableRentDays = 30,
                            Description = "Customers will feel comfortable and appreciate the size and quality of the outfit, The package will provide 12 products in 6 parkage:Shirt,Short,Skirt,Dress,Accessories,Costumes.Max product in each category is 4",
                            ImageUrl = "",
                            IsFeatured = false,
                            Name = "VIP Package",
                            NumOfProduct = 12,
                            Price = 800.0,
                            Status = 1
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "https://www.grab.com/vn/express/",
                            AreaId = 1,
                            Email = "Grap@gmail.com",
                            Name = "Grap",
                            OTP = "",
                            Password = "",
                            Phone = "123456",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "https://be.com.vn/",
                            AreaId = 1,
                            Email = "Grap@gmail.com",
                            Name = "Bee",
                            OTP = "",
                            Password = "",
                            Phone = "123456",
                            Status = 0
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Deposit")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdBrand")
                        .HasColumnType("int");

                    b.Property<int>("IdCategory")
                        .HasColumnType("int");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("IsUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IdBrand");

                    b.HasIndex("IdCategory");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AvailableQuantity = 20,
                            Color = "Blue",
                            Deposit = 100.0,
                            Description = "Men's and Women's Short Sleeve Shirt Loose Letter Couple Ins Shirt Multifunctional Vintage Half Sleeve UFO Shirt",
                            IdBrand = 1,
                            IdCategory = 1,
                            IsFeatured = false,
                            IsUsed = "False",
                            Name = "Cosmic Planet",
                            Price = 100f,
                            Quantity = 20,
                            Size = "M",
                            Status = "1",
                            Type = "New"
                        },
                        new
                        {
                            ID = 2,
                            AvailableQuantity = 20,
                            Color = "Grey",
                            Deposit = 110.0,
                            Description = "The ZHUXIA loose-fitting, short-sleeved shirt with a retro Japanese vintage style is a great choice for women's summer fashion.",
                            IdBrand = 2,
                            IdCategory = 1,
                            IsFeatured = false,
                            IsUsed = "False",
                            Name = "ZHUXIA-Shirt",
                            Price = 110f,
                            Quantity = 20,
                            Size = "X",
                            Status = "1",
                            Type = "New"
                        },
                        new
                        {
                            ID = 3,
                            AvailableQuantity = 20,
                            Color = "Black",
                            Deposit = 160.0,
                            Description = "Men's and Women's Short Sleeve Shirt Loose Letter Couple Ins Shirt Multifunctional Vintage Half Sleeve UFO Shirt",
                            IdBrand = 3,
                            IdCategory = 3,
                            IsFeatured = false,
                            IsUsed = "False",
                            Name = "Wide-leg retro-style Korean",
                            Price = 160f,
                            Quantity = 20,
                            Size = "X",
                            Status = "1",
                            Type = "New"
                        },
                        new
                        {
                            ID = 4,
                            AvailableQuantity = 20,
                            Color = "White",
                            Deposit = 100.0,
                            Description = "[HOT MODEL 2023] made of cool linen fabric, high-waisted with elastic waistband and drawstring for adjustable fit.",
                            IdBrand = 3,
                            IdCategory = 1,
                            IsFeatured = false,
                            IsUsed = "False",
                            Name = "Wide-leg women's pants",
                            Price = 150f,
                            Quantity = 20,
                            Size = "M",
                            Status = "1",
                            Type = "New"
                        },
                        new
                        {
                            ID = 5,
                            AvailableQuantity = 20,
                            Color = "Black",
                            Deposit = 100.0,
                            Description = "Gonz Wide-Fit Round Neck T-Shirt for Men and Women with Silk Screen Print, made of PC Cotton material.",
                            IdBrand = 3,
                            IdCategory = 1,
                            IsFeatured = false,
                            IsUsed = "False",
                            Name = "Gonz Wide-Fit Round Neck T-Shirt",
                            Price = 130f,
                            Quantity = 20,
                            Size = "M",
                            Status = "1",
                            Type = "New"
                        },
                        new
                        {
                            ID = 6,
                            AvailableQuantity = 20,
                            Color = "Pink",
                            Deposit = 100.0,
                            Description = "This vintage floral dress features a flattering A-line silhouette with a delicate floral print. Perfect for a summer day out or a casual evening event.",
                            IdBrand = 1,
                            IdCategory = 1,
                            IsFeatured = false,
                            IsUsed = "False",
                            Name = "Vintage Floral Dress",
                            Price = 200f,
                            Quantity = 20,
                            Size = "M",
                            Status = "1",
                            Type = "New"
                        },
                        new
                        {
                            ID = 7,
                            AvailableQuantity = 0,
                            Color = "White",
                            Deposit = 170.0,
                            Description = "Make a statement with this stunning floral maxi skirt. Its flowing design and beautiful floral pattern will turn heads wherever you go.",
                            IdBrand = 3,
                            IdCategory = 4,
                            IsFeatured = false,
                            IsUsed = "False",
                            Name = "Floral Maxi Skirt",
                            Price = 170f,
                            Quantity = 0,
                            Size = "XS",
                            Status = "1",
                            Type = "New"
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.ProductReturnOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReturnOrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReturnOrderId");

                    b.ToTable("ProductReturnOrders");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.ReturnOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateReturn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PartnerId");

                    b.ToTable("ReturnOrders");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberStars")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.ReviewImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.ToTable("ReviewImages");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateTransaction")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepositId")
                        .HasColumnType("int");

                    b.Property<string>("Paymethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepositId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0.0,
                            DateTransaction = new DateTime(2024, 6, 10, 20, 54, 42, 970, DateTimeKind.Local).AddTicks(505),
                            DepositId = 1,
                            Paymethod = "",
                            Status = 0,
                            WalletId = 1
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoldeId")
                        .HasColumnType("int");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<long>("OTP")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WalletCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WalletName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WalletPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OTP = 0L,
                            Status = 1,
                            WalletCode = "123",
                            WalletName = "Momo",
                            WalletPassword = "123"
                        });
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.CategoryPackage", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Category", "Category")
                        .WithMany("categoryPackages")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Package", "Package")
                        .WithMany("CategoryPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.CustomerPackage", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Customer", "Customer")
                        .WithMany("UserPackages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Package", "Package")
                        .WithMany("CustomerPackages")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Transaction", "Transaction")
                        .WithMany("CustomerPackages")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Package");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Deposit", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.FavouriteProduct", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Image", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.ItemInUserPackage", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.CustomerPackage", "UserPackage")
                        .WithMany("Items")
                        .HasForeignKey("UserPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("UserPackage");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Partner", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Area", "Area")
                        .WithMany("Partners")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Product", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("IdBrand")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.ProductReturnOrder", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.ReturnOrder", "ReturnOrder")
                        .WithMany("ProductReturnOrders")
                        .HasForeignKey("ReturnOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ReturnOrder");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.ReturnOrder", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Customer", "Customer")
                        .WithMany("ReturnOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Review", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Customer", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.ReviewImage", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Review", "Review")
                        .WithMany("ReviewImages")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Transaction", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Deposit", "Deposit")
                        .WithMany("Transactions")
                        .HasForeignKey("DepositId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deposit");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.User", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Wallet", b =>
                {
                    b.HasOne("SWD392.OutfitBox.DataLayer.Entities.Customer", "Customer")
                        .WithMany("Wallets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Area", b =>
                {
                    b.Navigation("Partners");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("categoryPackages");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Customer", b =>
                {
                    b.Navigation("ReturnOrders");

                    b.Navigation("Reviews");

                    b.Navigation("UserPackages");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.CustomerPackage", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Deposit", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Package", b =>
                {
                    b.Navigation("CategoryPackages");

                    b.Navigation("CustomerPackages");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.ReturnOrder", b =>
                {
                    b.Navigation("ProductReturnOrders");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Review", b =>
                {
                    b.Navigation("ReviewImages");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Transaction", b =>
                {
                    b.Navigation("CustomerPackages");
                });

            modelBuilder.Entity("SWD392.OutfitBox.DataLayer.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
